__author__ = 'tinglev'

class Data(object):

    DOCKER_CONF_FILE = 'DOCKER_CONF_FILE'

    IMAGE_NAME = 'IMAGE_NAME'
    IMAGE_VERSION = 'IMAGE_VERSION'
    PATCH_VERSION = 'PATCH_VERSION' 
    DOCKERFILE_FILE = 'DOCKERFILE_FILE'
    LOCAL_IMAGE_ID = 'LOCAL_IMAGE_ID'
    IMAGE_SIZE = 'IMAGE_SIZE'
    COMMIT_HASH = 'COMMIT_HASH'
    SEM_VER = 'SEM_VER'
    NPM_APPLICATION_VERSION = 'NPM_APPLICATION_VERSION'
    PACKAGE_JSON = 'PACKAGE_JSON'
    NPM_VERSION = 'NPM_VERSION'
    NPM_PACKAGE_NAME = 'NPM_PACKAGE_NAME'
    NPM_VERSION_CHANGED = 'NPM_VERSION_CHANGED'
