__author__ = 'tinglev'

class Data(object):

    DOCKER_CONF_FILE = 'DOCKER_CONF_FILE'
    DOCKER_FILE = 'DOCKER_FILE'
    LOCAL_IMAGE_ID = 'LOCAL_IMAGE_ID'
    IMAGE_SIZE = 'IMAGE_SIZE'
    IMAGE_VERSION = 'IMAGE_VERSION'
    IMAGE_VERSION_FROM_DOCKER_CONF = 'IMAGE_VERSION_FROM_DOCKER_CONF'
    IMAGE_NAME = 'IMAGE_NAME'
    COMMIT_HASH = 'COMMIT_HASH'
    SEM_VER = 'SEM_VER'
    
