__author__ = 'tinglev'

class Environment(object):

    IMAGE_NAME = 'IMAGE_NAME'
    IMAGE_VERSION = 'IMAGE_VERSION'
    PROJECT_ROOT = 'PROJECT_ROOT_PATH'
    GIT_COMMIT = 'GIT_COMMIT'
    BUILD_NUMBER = 'BUILD_NUMBER'
    SLACK_WEB_HOOK = 'SLACK_WEB_HOOK'
    SLACK_CHANNELS = 'SLACK_CHANNELS'
