__author__ = 'tinglev'

CONFIGURATION_FILE = 'CONFIGURATION_FILE'

# DOCKER
IMAGE_NAME = 'IMAGE_NAME'
IMAGE_VERSION = 'IMAGE_VERSION'
PATCH_VERSION = 'PATCH_VERSION'
DOCKERFILE_FILE = 'DOCKERFILE_FILE'
LOCAL_IMAGE_ID = 'LOCAL_IMAGE_ID'
IMAGE_SIZE = 'IMAGE_SIZE'
COMMIT_HASH = 'COMMIT_HASH'
SEM_VER = 'SEM_VER'
BUILD_ARGS = 'BUILD_ARGS'
IMAGE_TAGS = 'IMAGE_TAGS'

# NPM
PACKAGE_JSON = 'PACKAGE_JSON'
NPM_PACKAGE_VERSION = 'NPM_PACKAGE_VERSION'
NPM_PACKAGE_NAME = 'NPM_PACKAGE_NAME'
NPM_VERSION_CHANGED = 'NPM_VERSION_CHANGED'
NPM_MAJOR_MINOR_LATEST = 'NPM_MAJOR_MINOR_LATEST'
NPM_CONF_NODE_VERSION = 'NODE_VERSION'
NPM_CONF_ALLOW_CRITICALS = 'ALLOW_CRITICALS'
IGNORED_CRITICALS = 'IGNORED_CRITICALS'
